"""create initial schema

Revision ID: e6df2f7c0c11
Revises:
Create Date: 2026-09-14 06:59:45.639009

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6df2f7c0c11"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "country",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "denomination",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "era",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "issuer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "material",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "mint",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "coin",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=False),
        sa.Column("issuer_id", sa.Integer(), nullable=True),
        sa.Column("denomination_id", sa.Integer(), nullable=False),
        sa.Column("from_year", sa.Integer(), nullable=False),
        sa.Column("from_era_id", sa.Integer(), nullable=False),
        sa.Column("to_year", sa.Integer(), nullable=False),
        sa.Column("to_era_id", sa.Integer(), nullable=False),
        sa.Column("mint_id", sa.Integer(), nullable=True),
        sa.Column("material_id", sa.Integer(), nullable=True),
        sa.Column("state_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("weight", sa.Numeric(), nullable=True),
        sa.Column("diameter", sa.Numeric(), nullable=True),
        sa.Column("has_video", sa.Boolean(), nullable=False),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["country.id"],
        ),
        sa.ForeignKeyConstraint(
            ["denomination_id"],
            ["denomination.id"],
        ),
        sa.ForeignKeyConstraint(
            ["from_era_id"],
            ["era.id"],
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["issuer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["material.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mint_id"],
            ["mint.id"],
        ),
        sa.ForeignKeyConstraint(
            ["state_id"],
            ["state.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_era_id"],
            ["era.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("coin")
    op.drop_table("state")
    op.drop_table("mint")
    op.drop_table("material")
    op.drop_table("issuer")
    op.drop_table("era")
    op.drop_table("denomination")
    op.drop_table("country")
    # ### end Alembic commands ###
